### ISSUE TITLE
Thornlands 'orcchest' doesn't spawn

### ISSUE THREAD

**Issue by greatguys1** [MSRevive/map-sources#1]
After killing all of the 'rand_orcraid' orcs, a chest is supposed to spawn, but it never does. Test this via the following console commands:
`. dev_on wargwable`
`. usetrig rand_orcraid`

**Comment by Dridje** [comment]
![ThornlandsFixed](https://user-images.githubusercontent.com/3627427/194739925-d5cf14e9-ef70-4d09-a729-6de88c70ef37.jpg)

As we have no official source for Thornlands and decompiling definitely doesn't work (we've tried previously), I have used ripENT to modify and submit the changes.

Fixing the forrest/forest typo was VERY easy.
The transition was easy as well and you will transition to the correct spawns when you head back from thorn_north.  Also modified the angles so you face towards the field instead of the transition.

The orc_raid used the "fireallperish" flag in the entity properties.  This is supposed to keep track and trigger when everything using the monsterspawn has fully died (all lives gone).  This is listed as buggy in the editor and was recommended NOT to use it like that.  I added a new ms_counter entity in the map that will track each death from each orc life and when it counts to 13 (total orcs) it triggers the chest to spawn.

I also modified the spectator entity so you get a nice view of the field instead of the half rock floating in the air view. 
![20221008223114_1](https://user-images.githubusercontent.com/3627427/194740163-b1db53d1-5a70-4c58-9a44-29113dc7ac46.jpg)

**Comment by Dridje** [comment]
Also noticed that boar that was still spawning inside a tree and checked it out.  Same problem as mines, the monsterspawn box intersects the tree and it uses the spawn anywhere within box.  Changed that specific spawner to use NPC location instead.
