### ISSUE TITLE
Mines: Some of the animals spawn stuck in the hills prior to the cave

### ISSUE THREAD

**Issue by greatguys1** [MSRevive/map-sources#4]

**Comment by Dridje** [comment]
Looking into this issue now...
I think what may be happening is the msarea_monsterspawn is a giant box, intersecting with the hills and the monster spawns are set to spawn within the box.

**Comment by Dridje** [comment]
![MinesProblem](https://user-images.githubusercontent.com/3627427/194728666-fd5bb02d-5f72-4870-997f-b95e2b901252.png)

Figured it out.  The mapper's intention was to have the monstesr spawn inside any of those individual boxes but the spawn "random, within box" property with multiple individual brushes causes the box to take on the dimensions of the furthest brush in each direction (thick red line).  You can see how big the box is by looking at the red dotted line when you select the brushes in an editor.

As you can see, the hill is directly inside that box.

Since we don't have a map file (I used a de-compiler to investigate), this can be fixed by changing the spawns to "at monster placement" and giving each monster placement a unique coordinate on the surface.  It won't be random anymore but monsters won't be stuck either.

**Comment by Dridje** [comment]
Map is now fixed.

Set the monsterspawn to spawn @ monster placement and gave each NPC using said spawner a unique coordinate to spawn at.
Saw tree on the hill that was not lit up (not affected by the level's light), removed said tree.
